### ISSUE TITLE
HACS

### ISSUE THREAD

**Issue by magnar81** [djbulsink/panasonic_ac#13]
Add this to HACS with a little instruction how to get it working.
I just installed it manually via HACS and i just love it!

**Comment by inforsgit** [comment]
I had a look at some HACS implementation a while back for another project, I can try and take a look and then create a PR.

**Comment by inforsgit** [comment]
Ok...added the latest sidecar files to get HACS to properly manage panasonic_ac as PR #14 . To actually have this automatically appear in HACS then @djbulsink needs to add a PR to this file https://github.com/custom-components/hacs/blob/data/repositories/integration to add djbulsink/panasonic_ac (this is described here https://hacs.netlify.com/developer/include_default_repositories/).

**Comment by magnar81** [comment]
Ok, hope it will be done because this is a great addon for homeassistant.

**Comment by djbulsink** [comment]
The integration is now available as default repository in HACS. Thanks @inforsgit
