### ISSUE TITLE
HA 0.89.0 compatibility

### ISSUE THREAD

**Issue by rest77** [djbulsink/panasonic_ac#2]
In 0.89.0 the panasonic component is not working anymore... I did some quick changes to get it running again:

from homeassistant.components.climate import (
    ClimateDevice, STATE_HEAT, STATE_COOL,
    STATE_AUTO, STATE_DRY, STATE_FAN_ONLY,
    SUPPORT_TARGET_TEMPERATURE, SUPPORT_FAN_MODE, 
    SUPPORT_OPERATION_MODE, SUPPORT_SWING_MODE,
    SUPPORT_ON_OFF, PLATFORM_SCHEMA)

changed to:

from homeassistant.components.climate import ClimateDevice, PLATFORM_SCHEMA
from homeassistant.components.climate.const import (
    STATE_HEAT, STATE_COOL,
    STATE_AUTO, STATE_DRY, STATE_FAN_ONLY,
    SUPPORT_TARGET_TEMPERATURE, SUPPORT_FAN_MODE, 
    SUPPORT_OPERATION_MODE, SUPPORT_SWING_MODE,
    SUPPORT_ON_OFF)

I don't if that is all and I have no idea how to push this change but some one can for sure :-)

/Reik

**Comment by djbulsink** [comment]
Hi @rest77, thanks for reporting this issue. It is resolved in pull request #3
