### ISSUE TITLE
Broken due to authentication error

### ISSUE THREAD

**Issue by Expecho** [djbulsink/panasonic_ac#39]
It seems there have been changes to the API. Home assistant logs tell there is an authentication issue.

**Comment by teamsuperpanda** [comment]
I believe this integration is based on [python-panasonic-comfort-cloud](https://github.com/lostfields/python-panasonic-comfort-cloud/). 

Reading their issues they mention a 403 error which I am getting.
[403 Forbidden](https://github.com/lostfields/python-panasonic-comfort-cloud/issues/64)

**Comment by teamsuperpanda** [comment]
Update Manifest.json to the following and it will work again

`{
  "domain": "panasonic_ac",
  "name": "Panasonic AC",
  "documentation": "https://github.com/djbulsink/panasonic_ac/",
  "dependencies": [],
  "codeowners": ["Djbulsink", "SeraphimSerapis"],
  "requirements": ["pcomfortcloud==0.0.23"],
  "version": "1.0.1"
}
`
