### ISSUE TITLE
Devices unavailable 

### ISSUE THREAD

**Issue by andrewf6** [djbulsink/panasonic_ac#44]
Maybe the recent updates to the library by lostfields corrects the issue. 
https://github.com/lostfields/python-panasonic-comfort-cloud/issues/82#issue-comment-box

Unfortunately I don't have the skills to update this repo. Hopefully someone can help?
@SeraphimSerapis ?

**Comment by SeraphimSerapis** [comment]
https://github.com/djbulsink/panasonic_ac/commit/6077debaf5ace73e04d7ce8056db4e37e265b241 the last version of the library is already used. I'm currently not using this component anymore, so I have no means to test what may cause your issue

**Comment by andrewf6** [comment]
Apologies, for wasting your time, I wrote the issue last week but forgot to save it. I'm the meantime someone's done the work.
