### ISSUE TITLE
Add support for setting Eco (Quiet/Powerful/Auto) Mode

### ISSUE THREAD

**Issue by inforsgit** [djbulsink/panasonic_ac#8]
The python-panasonic-comfort-cloud library used by this component supports setting of the Eco mode of the device (Quiet, Powerful or Auto). It would be good to have this supported by this component so that it could be adjusted by Home Assistant.

For implementation is should be straightforward to call this, it would be a call to the EcoMode contant from pcomfortcloud's constants. As far as integration using the climate integration goes, I assume this would be implemented in the 0.96 onwards HA climate integration as a preset mode.

**Comment by djbulsink** [comment]
Hi @inforsgit ,

In [feature branch](/djbulsink/panasonic_ac/tree/feature/eco-mode) I added support for EcoMode. Would you like to test it?

**Comment by inforsgit** [comment]
Sure thing, thanks so much! I’ll get back to you.

**Comment by inforsgit** [comment]
Hmmm...no luck at the moment - it doesn't seem to load the device at all. I've got debug turned on and with the master branch I see the messages about setting up my device. If I use the new climate.py though there is still the HA message

`[homeassistant.loader] You are using a custom integration for panasonic_ac which has not been tested by Home Assistant. `...

but nothing (no debug messages about setting up my AC device) after that. I'm not sure why this could be but I'm happy to provide more info if there's some debugging that can be done.

**Comment by djbulsink** [comment]
@inforsgit . Ow that's unexpected behavior. I would expect some debug message about setting up devices or syntax error messages. I'm not sure i pushed the latest version last time. The last commit fixed a issue causing the the loading of preset modes to fail.

Also I found out that ecomode was not implemented fully in the pcomfortcloud library . I made a pr for this https://github.com/lostfields/python-panasonic-comfort-cloud/pull/6 .

**Comment by inforsgit** [comment]
Ooh...well spotted that the pcomfortcloud library didn't properly support it, I should have tested that too ;)

When I'm back tonight I'll try and do a little bit of playing to see if I can get to the bottom of why it's not even appearing.

**Comment by inforsgit** [comment]
#10 gets a bit further to working status - it now loads and appears on the GUI. I notice there are 4 options in the GUI dropdown: the three modes plus  'None'. Perhaps setting `Auto` mode should be removed and use the HA `None` mode to represent the Panasonic `Auto` mode?

**Comment by inforsgit** [comment]
I've tested this and confirmed it's working - "Eco" and "Boost" are used rather than "Quiet" and "Powerful" but it's understandable enough :)
